DA#95: Modified: Fix refresh collections
couchbaselabs/VSCode-Couchbase pull request #124
Opened 2023-02-17 09:51 UTC by AayushTyagi1

## Describe the problem this PR is solving
Refresh collections not working

## Short description of the changes
On click on refresh collections the bucket is getting refreshed so that it could refresh whole tree.

2023-02-17 14:08 UTC, MikeGoldsmith requested changes

2023-02-20 07:45 UTC, AayushTyagi1 commented on src/extension.ts
> +        clusterConnectionTreeProvider.refresh(node.parentNode);
The problem with the above code is that when it was refreshing parentNode, the childNode i.e. the collection we have
![Screenshot 2023-02-20 at 12 59 00 PM](https://user-images.githubusercontent.com/42893909/220043627-eeec5aa3-8374-4bb7-a7dc-28b3caf5a1f4.png)
 created has not yet updated and it is giving us the below error message.

2023-02-20 07:46 UTC, AayushTyagi1 commented on src/extension.ts
> +        clusterConnectionTreeProvider.refresh(node.parentNode);
@MikeGoldsmith Can you please try it few times at your end. You will get to see the error.

2023-02-21 10:24 UTC, MikeGoldsmith commented on src/extension.ts
> +        clusterConnectionTreeProvider.refresh(node.parentNode);
As in #123 - I don't see how a document not found error can be caused by refreshing the tree but not duplicating the refresh call is an optimisation we can do later.

2023-02-21 10:24 UTC, MikeGoldsmith approved these changes

2023-02-21 10:24 UTC, merged