DA-118: Modified: Retrieve existing document content when creating ne…
couchbaselabs/VSCode-Couchbase pull request #92
Opened 2023-01-20 08:33 UTC by AayushTyagi1

Current Behaviour: While we are creating a new document with the same name which already exist we are getting the new document with empty content and the current document’s content get erased. 

Expected Behaviour: While we are creating a new document with the same name which already exist we should get the document with existing content.

2023-01-20 13:28 UTC, MikeGoldsmith requested changes
This looks good - thanks @AayushTyagi1 👍🏻 

I've left some feedback on code style and a suggestion for moving the call to write the JSON to a local file to after the try/catch block.

2023-01-20 13:28 UTC, MikeGoldsmith commented on src/extension.ts
> +        const uri = vscode.Uri.parse(`couchbase:/${node.bucketName}/${node.scopeName}/${node.collectionName}/${documentName}.json`);
Looks like your indentation has got mixed up. This should be one increment to the left. Same for the closing brackets on 209.

2023-01-20 13:28 UTC, MikeGoldsmith commented on src/extension.ts
> +        try {
So the intention is to try to retrieve the document with the same key first, then if if returns an error we create a new empty document instead. Please can you add a code comment to describe this behaviour?

2023-01-20 13:28 UTC, MikeGoldsmith commented on src/extension.ts
> +          memFs.writeFile(
We're using `memFs.writeFile` in both the try and catch blocks with the only difference being the document body. Could we move this to outside of the try/catch to only call it once, with either the existing document body or an empty body?

2023-01-21 15:52 UTC, AayushTyagi1 commented
I have resolved the comment. We need to have same code formatting settings going forward. 
Please review again.

2023-01-23 12:34 UTC, MikeGoldsmith approved these changes
Looks good 👍🏻

2023-01-27 09:33 UTC, merged